### ISSUE TITLE
Не работает RTC в дс (дам 100 - 300 рублей, тк я уже устал)

### ISSUE THREAD

**Issue by ImHartash** [Flowseal/zapret-discord-youtube#1170]
Сразу после блокировки обходы не работают. Пробовал все способы (Flowseal не закрывай) и много обходов, делал так, сяк. Мое предположение что это из за роутера возможно. Готов сделать все что скажете. Т.к эта проблемы меня съела полностью, и я в тильте уже, я готов дать денег до 300 рублей. Буду рад за все, деньги дам если сработает. Роутер МГТС, провайдер Сибирский Медвед. Все что попросите - дам (скрины, настройки и тд).

**Comment by ma3uk** [comment]
Бросьте вы все эти костыли и переходите на связку Discord-drover + Verge Clash + AmneziaWG с WARP профилем. Если нужна помощь, то пингани в дискорде по нику MyonezGG

**Comment by ma3uk** [comment]
Короче, 

1. Качаешь последнюю версию или альфа версию Clash Verge https://github.com/clash-verge-rev/clash-verge-rev/releases
2. Качаешь Discord-drover https://github.com/hdrover/discord-drover/releases
3. Устанавливаешь Clash Verge, после установки ставишь русский язык интерфейса
4.  Копируешь конфиг и создаешь текстовый файл в который его вставляешь, файлу делаешь любое имя с расширением .yaml
```
mode: rule
ipv6: false
unified-delay: true
tcp-concurrent: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  # Bootstrap DNS
  default-nameserver: ['1.1.1.1', '1.0.0.1', '8.8.8.8', '8.8.4.4']
  # Upstream DNS
  nameserver: ['https://1.1.1.1/dns-query', 'https://8.8.8.8/dns-query', 'https://1.0.0.1/dns-query', 'https://8.8.4.4/dns-query']
  find-process-mode: off

profile:
  store-selected: true
  store-fake-ip: true

routing-mark: 2 # Prevent cyclic redirection

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - 'Mijia Cloud'

proxies:
  - name: 'amnezia_wg'
    type: wireguard
    private-key: #заменить приватным ключом из конфига
    server: 188.114.97.66
    port: 3138
    ip: 172.16.0.2
    ipv6: 2606:4700:110:84af:f24d:ad27:9987:fa28
    public-key: #заменить публичным ключом из конфига
    allowed-ips: ['0.0.0.0/0', '::/0']
    udp: true
    mtu: 1280
    amnezia-wg-option:
      jc: 120
      jmin: 23
      jmax: 911
      s1: 0
      s2: 0
      h1: 1
      h2: 2
      h4: 4
      h3: 3 
      
proxy-groups:
  - name: PROXY_WG
    type: select
    disable-udp: false
    proxies: [amnezia_wg]

rule-providers:
  Discord:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/discord.yaml'
    format: yaml
    proxy: DIRECT
    interval: 84000
  
  DiscordIP:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/discord-ip-short.yaml'
    format: yaml
    proxy: DIRECT
    interval: 84000
  
  Antifilter:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/antifilter-community-domain.yaml'
    format: yaml  
    proxy: DIRECT
    interval: 84000
  
  AntifilterIP:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/antifilter-ip.yaml'
    format: yaml
    proxy: DIRECT
    interval: 84000
    
  AntifilterIPComm:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/antifilter-community-ip.yaml'
    format: yaml
    proxy: DIRECT
    interval: 84000
  
  Add:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/add.yaml'
    format: yaml
    proxy: DIRECT
    interval: 84000
    
  Youtube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ma3uk/sing-box-rules/refs/heads/main/yaml/youtube.yaml"
    format: yaml
    proxy: DIRECT
    interval: 84000

rules:
  - DOMAIN-SUFFIX,speedtest.net,PROXY_WG
  - RULE-SET,Discord,PROXY_WG
  - RULE-SET,DiscordIP,PROXY_WG
  - RULE-SET,Antifilter,PROXY_WG
  - RULE-SET,AntifilterIPComm,PROXY_WG
  - RULE-SET,AntifilterIP,PROXY_WG
  - RULE-SET,Add,PROXY_WG
  - RULE-SET,Youtube,PROXY_WG
  - MATCH,DIRECT

```
5. Переходишь на сайт https://terminator.aeza.net/en/ выбираешь Debian
6. В запустившейся консоли вставляешь `bash <(wget -qO- https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh)`
7. Получаешь конфиг который качаешь по ссылке которую тебе дадут в консоли, либо просто конфиг копируешь и вставляешь в какой-нибудь текстовый файл.
8. Открываешь полученный из консоли конфиг и конфиг yaml который создали раньше и переносишь значения PrivateKey в private-key и PublicKey в public-key, сохраняешь YAML конфиг.
9. Запускаешь Clash Verge заходишь в вкладку "Профили", нажимаешь кнопку "Новый", ставишь Тип Local, снизу нажимаешь кнопку "Выбрать файл" и выбираешь сохраненный YAML конфиг, сохраняем.
10. Распаковываешь discord-drover в папку, где находится Discord.exe именно в нее
11. Открываешь файл drover.ini в строке proxy меняешь порт в IP адресе на 7897, сохраняешь файл.
12. Если нужно, чтоб работал ютуб, то заходишь в настройки Clash Verge и включаешь "Системный прокси"
13. Перезапускаем Discord и проверяем
